name: Update Changelog

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch full history and tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate changelog for Unreleased only
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s --release-count 0

      - name: Show updated changelog
        run: cat CHANGELOG.md

      - name: Commit changelog if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git diff --cached --quiet || git commit -m "docs(changelog): update Unreleased section [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
